name: Backup to S3
on:
  schedule:
    - cron: "0 2 * * 0"
  workflow_dispatch:
jobs:
  backup:
    uses: Specter099/.github/.github/workflows/repo-backup.yml@main
    with:
      s3-bucket: github-repo-backup-1b114b0d7fd4
    secrets: inherit
    permissions:
      id-token: write
      contents: read
